import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/widgets/header";

import "@/assets/css/globals.css";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bricolageGrotesque.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          <Header />

          {/* Entire Content */}

          {children}

          <div className="fixed inset-0 -z-10 max-w-screen-xl mx-auto border-x pointer-events-none border-dashed" />
        </ThemeProvider>
      </body>
    </html>
  );
}
