import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import { Guidelines } from "@/components/guidelines";

import { Header } from "@/widgets/header";

import "@/assets/css/globals.css";
import { Footer } from "@/widgets/footer";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bricolageGrotesque.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          <Header />

          {/* Entire Content */}
          {children}

          {/* Footer */}
          <Footer />

          {/* Guidelines / Rulers on the entire page */}
          <Guidelines isFixed />
        </ThemeProvider>
      </body>
    </html>
  );
}
